version: '2'

services:

  mariadb:
    image: mariadb:10.1.20
    hostname: mariadb
    volumes:
      - ./docker_volumes/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=kotlin
      - MYSQL_ROOT_PASSWORD=password

